### ISSUE TITLE
Unclear how `containsPoint` is meant to be used?

### ISSUE THREAD

**Issue by clarkdave** [martianboy/postgres-range#3]
The implementation of `containsPoint` seems to expect the lower and upper will have a `compareTo` method, but this isn't documented and it's not obvious how this would work in practice, as ranges will typically be numbers or dates which won't have a `compareTo` method.

For example:

```js
intRange = range.parse('[1, 10)', x => parseInt(x))
// Range { lower: 1, upper: 10, mask: 4 }
intRange.lower
// 1
intRange.upper
// 10
intRange.containsPoint(5)
// Uncaught TypeError: this.lower.compareTo is not a function
```

I note that there's currently no test coverage for `containsPoint` or `containsRange`, so perhaps they're not ready for use yet? However, they are included in the TypeScript types so they appear to be public.

Thanks!

**Comment by martianboy** [comment]
Thanks for reporting this! Not sure where the `.compareTo()` came from, I think it's from the Java package which is the inspiration for this one. It should be fixed now, just update to the latest version which is 1.1.2. But if you found any other issue with it please do let me know! Also PRs are welcome on any aspects of the module. ;)

**Comment by martianboy** [comment]
@clarkdave I'm going to close this issue. Feel free to re-open if you have anything else to add.
